import {
    IconBrandGoogleHome,
    IconCheck,
    IconChevronLeft,
    IconChevronRight,
    IconLoader2,
    IconLogout,
    IconMoodEmptyFilled,
    IconPlus,
    IconSquareRoundedXFilled,
    IconStarFilled,
    IconTruckDelivery,
    IconVocabulary,
    IconX,
    IconSmartHome,
    type Icon as TablerIcons,
    IconSearch,
    IconBell,
    IconUser,
    IconQuestionMark,
    IconGardenCart,
    IconBrandFacebook,
    IconBrandDiscord,
    IconBrandTwitter,
    IconBrandGithub,
    IconBrandDribbble,
    IconSearch,
    IconBell,
    IconUser,
    IconQuestionMark,
    IconGardenCart,
    IconBrandFacebook,
    IconBrandDiscord,
    IconBrandTwitter,
    IconBrandGithub,
    IconBrandDribbble,
} from "@tabler/icons-react";

export type Icon = TablerIcons;

export const Icons = {
    logo: IconVocabulary,
    close: IconX,
    squareClose: IconSquareRoundedXFilled,
    home: IconBrandGoogleHome,
    signOut: IconLogout,
    loader: IconLoader2,
    emptyFilled: IconMoodEmptyFilled,
    plus: IconPlus,
    check: IconCheck,
    chevronLeft: IconChevronLeft,
    chevronRight: IconChevronRight,
    star: IconStarFilled,
    truckDelivery: IconTruckDelivery,
    smartHome: IconSmartHome,
    search: IconSearch,
    bell: IconBell,
    user: IconUser,
    question: IconQuestionMark,
    cart: IconGardenCart,
    fb: IconBrandFacebook,
    disc: IconBrandDiscord,
    tw: IconBrandTwitter,
    git: IconBrandGithub,
    dribble: IconBrandDribbble,
    search: IconSearch,
    bell: IconBell,
    user: IconUser,
    question: IconQuestionMark,
    cart: IconGardenCart,
    fb: IconBrandFacebook,
    disc: IconBrandDiscord,
    tw: IconBrandTwitter,
    git: IconBrandGithub,
    dribble: IconBrandDribbble,
};
